### PR TITLE
Add SciPy Windows support

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@cryos @utkarshayachit This PR adds the SciPy Windows support to the superbuild.

**Comment by cryos** [comment]
Looks good to me.

**Comment by Hovden** [comment]
Is there a reason why the "nightly" build for mac does not provide a download package on cdash? I can test the native SciPy support on OSX once one is posted.

**Comment by cryos** [comment]
That is new, and even ones I know had a binary (because I downloaded them and tested them) don't appear to have one any longer. @mathturtle, @cjh1 any ideas on this? Did something change with CDash? https://open.cdash.org/index.php?project=TomViz&date=20150630 shows no binary packages now, but most certainly had them at the time when I was visiting Cornell for example.

**Comment by cryos** [comment]
We may be hitting a file quota limit, I just increased it from 1GB to 10GB (the addition of SciPy increased the package size quite a bit). This would explain the old packages being deleted too. I will see about triggering a new build.

**Comment by mathturtle** [comment]
Today's builds on windows had a binary uploaded to cdash.  I'm not sure
what happened on the mac, there is no error message in the log file, so the
ctest side thinks the upload was successful.  I've talked with Ben, and he
suggested that we take a look at the file size limit on the tomviz cdash
and make sure that the disk isn't full.

**Comment by mathturtle** [comment]
The rsync to the tomviz website didn't have any errors.  What is the link
that that goes to?  Rob could get the package from there too.

**Comment by Hovden** [comment]
There is no download link for the mac on cdash. The downloadable links appear as little package "box" icons. The most current builds in cdash only have downloadable packages for Windows.

Could you provide the link you are referring to?

**Comment by Hovden** [comment]
Not all of the SciPy libraries are working, in particular those in ndimage. If you run the Image Rotate transform that is included in the build you will get the following error:

Failed to execute the script.
Traceback (most recent call last):
  File "Rotate", line 14, in transform_scalars
  File "/Volumes/tomviz-0.5.1-Darwin-64bit/tomviz.app/Contents/Python/scipy/ndimage/__init__.py", line 172, in <module>
    from .filters import *
  File "/Volumes/tomviz-0.5.1-Darwin-64bit/tomviz.app/Contents/Python/scipy/ndimage/filters.py", line 35, in <module>
    from . import _ni_support
ImportError: cannot import name _ni_support

**Comment by cjh1** [comment]
Just to confirm "from scipy import ndimage" works on a Windows build.

**Comment by cjh1** [comment]
Can you run otool -L on /Volumes/tomviz-0.5.1-Darwin-64bit/tomviz.app/Contents/Python/scipy/ndimage/_nd_image.pyd and paste the result.

**Comment by Hovden** [comment]
As you figured out, I was using OSX, sorry about the lack of detail. Also, for more clarification, I can run "import scipy as sp" but I cannot run "from scipy import ndimage"

Here is my output for your request:
otool -L /Volumes/tomviz-0.5.1-Darwin-64bit/tomviz.app/Contents/Python/scipy/ndimage/_nd_image.pyd
error: otool: can't open file: /Volumes/tomviz-0.5.1-Darwin-64bit/tomviz.app/Contents/Python/scipy/ndimage/_nd_image.pyd (No such file or directory)

However, there is a _nd_image.so file:
otool -L /Volumes/tomviz-0.5.1-Darwin-64bit/tomviz.app/Contents/Python/scipy/ndimage/_nd_image.so
/Volumes/tomviz-0.5.1-Darwin-64bit/tomviz.app/Contents/Python/scipy/ndimage/_nd_image.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)

**Pull request merged**
