### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by thewtex**
This are a couple of patches that make steps towards a Linux Docker build, although they would be good to integrate in general.  I will make further comments in Issue #78

### CODE REVIEW

**Comment by mathturtle** [comment]
@mathstuf Have you seen this repo he is using for python?  Would it be something we are interested in porting to common-superbuild at some point?

**Comment by mathstuf** [comment]
I've seen a couple of them. I don't keep constant track of the status of CMake'd Python. I think the problem with it had to do with static builds or something on Windows. Or maybe it didn't make a proper module set on Windows at all? ISTR something about not being able to use hashlib or some compression module on Windows with the last CMake build I tried.

**Comment by thewtex** [comment]
The only Windows limitation I am aware of is the ctypes module with a Visual Studio 2012 or earlier generator.

**Comment by cryos** [comment]
Is this still relevant, @mathturtle did you integrate relevant suggestions into the Docker image you have been working on?

**Comment by mathturtle** [comment]
So the Qt4 changes are no longer relevant anyway and as for python I think we should prefer to use the release rather than a CMakeified version of it.  I'm not sure it really matters though.

**Comment by thewtex** [comment]
On a side note, the CMake-ified Python version is coming along nicely and now support Python 3.5

**Comment by cryos** [comment]
I would like to play with the CMake-ified Python, maybe we can talk more about this. It is something that is a little orthogonal to this pull request, but I would like to see how we might start working with it, whether it works on all the platforms. It seems like the best way to go, especially if it can use later versions of Visual Studio, etc.

**Pull request closed without merging**
