### PR TITLE
Move ParaView forward

### PR DESCRIPTION
**Pull request by cquammen**
Brings in support for:

* dockable console widget
* direct scalar coloring of textures by floating point types for
  Slice and Orthogonal Slice modules.

### CODE REVIEW

**Comment by cquammen** [comment]
We can merge #1257 after this is merged.

**Comment by cjh1** [comment]
I will rebuild the CI ParaView builds

**Comment by cquammen** [comment]
Thanks, @cjh1!

**Comment by mathturtle** [comment]
OpenChemistry/tomviz#1242 is blocked on this as well (I need a ParaView more recent than Aug 18th for that one I think).

**Comment by cjh1** [comment]
@mathturtle So you need a more recent SHA? Can we batch this if that is that case?

**Comment by mathturtle** [comment]
No, I think that one will work.  It looks like it is from September 8th.  @cryos told me to hold off on updating ParaView then since we had just bumped for your threading branch and he wants to move less often.

**Comment by cjh1** [comment]
Ok, I will go head a rebuild using this SHA then, thanks.

**Comment by cquammen** [comment]
Is the process such that you build this on the CI machines and if all goes well merge this?

**Comment by cjh1** [comment]
I have to build on machines that "look like" the CI machines. We can go ahead a merge this I think.

**Pull request merged**
