### PR TITLE
Remove ParaView version from librarys and directory names

### PR DESCRIPTION
**Pull request by mathturtle**
This will prevent having to modify tomviz superbuild every time
ParaView's version changes.

### CODE REVIEW

**Comment by cryos** [comment]
That looks great, assuming it works then we should definitely use this, I didn't realize ParaView just used the underlying VTK install variables.

**Comment by mathturtle** [comment]
Apparently it does.  I asked Ben how to switch it and he said you just set these variables.  I was expecting it to be much harder like the 'don't use qhelpgenerator' patch.

**Comment by cryos** [comment]
You have a typo in the commit message, should be singular library, nice fix. I still feel like a simple flag in ParaView to remove version numbers would be nice, but this gets us what we need.

**Comment by utkarshayachit** [comment]
Look at `vtk_target_name` function in vtkModuleMacros.cmake. Just define `VTK_CUSTOM_LIBRARY_SUFFIX` and you'll get what you want, I believe.

**Comment by mathturtle** [comment]
@utkarshayachit I did set that to the empty string. The others control the install paths.  We don't want things installed under lib/paraview-x.y (as it is now we have to modify the cpack scripts in tomviz superbuild every time the version changes).  The other changes force things to install into lib/paraview (or share/paraview, etc).

**Comment by utkarshayachit** [comment]
@mathturtle yea, I saw that after I had posted the comment and hence I promptly removed it ;), but not before you read it, it seems :).

**Pull request merged**
