### PR TITLE
Fixes for debian7

### PR DESCRIPTION
**Pull request by mathturtle**
These are the (tentative) fixes needed for linux builds to work.  There are a few packaging fixes too, but I don't think I have all of those finished yet.

### CODE REVIEW

**Comment by mathturtle** [comment]
@cryos I think we have to merge this to test it on the current platforms.  There are only a few minor changes that even *could* affect them, but the buildbot 'force build' feature seems to be broken right now and isn't letting me build from this branch.

**Comment by cryos** [comment]
Nothing jumps out at me, I think we should merge this and fix any issues you see on the dashboards.

**Comment by mathturtle** [comment]
Ok.  As soon as I have the debian7 dashboard connected to buildbot, I plan to merge this.

Waiting on: https://kwgitlab.kitware.com/buildbot/buildbot/merge_requests/665

**Comment by mathturtle** [comment]
Now that we have a linux builder, merging this.

**Comment by cryos** [comment]
Great work Shawn, looking forward to getting these binaries up and running.

**Comment by Hovden** [comment]
Cool!

**Pull request merged**
