### PR TITLE
Tomviz hash in binaries

### LINKED ISSUE #25: add hash to tomviz binary names
Copy mechanisms from paraview superbuild. A symlink should also be uploaded for `tomviz-latest.$ext` from the buildbot master (add extra factory steps).

### PR DESCRIPTION
**Pull request by mathstuf**
---
Depends on #24. Also fixes #25. Running tests locally first.

### CODE REVIEW

**Comment by mathturtle** [comment]
Doesn't this have the same problem as #25 in that it undoes my LDFLAGS changes for scipy?

**Comment by cryos** [comment]
@mathturtle it does, could you extend this (as @mathstuf did) and bring your SciPy LDFLAGS work back to the tip please.

**Comment by mathstuf** [comment]
Yeah, it's just rebased on top of #24. When #24 is merged, I'll rebase again.

**Comment by cryos** [comment]
@mathturtle, as above - it is tomviz in lower case. I think you may need to simply hand port this, and work with @mathstuf on getting the auto-upload of binaries/a consistent symlink to the latest binary that I can link to from our web site.

**Comment by mathstuf** [comment]
Looks like this has been merged; closing. @mathturtle The buildbot branch should be similar to what ParaView does right now.

**Comment by mathturtle** [comment]
When I based my branch on this one, I think you pushed an update and I didn't rebase on your update before mine was merged... So this was never closed.

**Comment by cryos** [comment]
Either way the binaries do not have the hash in their file name, so the actual feature was never merged.

**Pull request closed without merging**
