### PR TITLE
DetermineTomvizVersion: check the right variable

### PR DESCRIPTION
**Pull request by mathstuf**
@cryos

### CODE REVIEW

**Comment by mathturtle** [comment]
I was trying to figure out why this wasn't working last night...

**Comment by cryos** [comment]
Cool, merging to check out the result, then we just need to get the upload piece working so that I can add links to the website.

**Comment by mathstuf** [comment]
I think the symlink should be made just fine; it uses the same setup as ParaView in buildbot.

**Comment by mathstuf** [comment]
Ooh, nevermind, that part isn't enabled. Will point @mathturtle to the right place to fix it.

**Comment by cryos** [comment]
Sounds good - once they are made please verify, and give me the correct URL to add to our downloads page.

**Pull request merged**
