### PR TITLE
Fix Linux build's python environment (and possibly OSX too)

### PR DESCRIPTION
**Pull request by mathturtle**
I tested this on OSX to make sure it works.

### CODE REVIEW

**Comment by mathturtle** [comment]
Updated to move the rest of the macOS-specific stuff inside the `if(APPLE)` block.  This seems to work fine locally on Linux.

**Comment by cryos** [comment]
Sounds good, as far as I can tell https://open.cdash.org/index.php?project=TomViz&date=2017-07-24 has a passing Mac dashboard, I see "The Python include directory is not the same for both ParaView and ITK." causing an error for Linux - you may need to add the flag to relax the check on ITK/ParaView using the same Python as it compares the include directory path I think.

**Comment by mathturtle** [comment]
Updated to disable those checks @cryos.

**Comment by cryos** [comment]
Sounds good, let's merge this and see how the builds look.

**Pull request merged**
